Slovak language added > modified:   resources/messages/en/app.php
yiisoft/demo pull request #487
Opened 2022-07-31 21:47 UTC by evan70

modified:   resources/messages/id/app.php Slovak language added
	modified:   resources/messages/ru/app.php Slovak Language added
	new file:   resources/messages/sk/app.php Slovak language file
	new file:   resources/rbac/assignments.php Slovak language added
	modified:   views/layout/main.php Slovak language added

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2022-07-31 21:50 UTC, evan70 commented
Slovak language added

2022-07-31 21:56 UTC, evan70 commented
Scrutinizer fails to build in step titled :

In LocalServer.php line 163:
                                                                               
Code coverage file /home/scrutinizer/build/runtime/tests/_output/c3tmp/code  
  coverage.serialized does not exist  

... ending up with message :
The coverage file '/home/scrutinizer/build/runtime/tests/_output/coverage.xml' was not found.

2022-07-31 22:02 UTC, xepozz requested changes

2022-07-31 22:02 UTC, xepozz commented on resources/rbac/assignments.php
> +<?php
Is it necessary?

2022-07-31 22:04 UTC, xepozz commented
> Scrutinizer fails to build in step titled :
> 
> In LocalServer.php line 163:
> 
> Code coverage file /home/scrutinizer/build/runtime/tests/_output/c3tmp/code coverage.serialized does not exist
> 
> ... ending up with message : The coverage file '/home/scrutinizer/build/runtime/tests/_output/coverage.xml' was not found.

Don't worry about it.

2022-08-01 09:07 UTC, closed without merging

2022-08-01 10:29 UTC, xepozz commented
@evan70 why did you close it?

2022-08-01 21:49 UTC, evan70 commented
i was hungry maybe, it does't matter, one mistake follow another one :)
thX ;) there's much more time to push it later ...  sorry 4 bumpin'