YiiSoft | Proposal to structure demo application
yiisoft/demo pull request #494
Opened 2022-08-08 09:27 UTC by maximniko

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌

I took some time to form a more convenient application structure.
If you accept my offer, check the work of the tests.
Failed to quickly launch the application and tests as described in Readme.md

Я уделил немного времени для формирования более удобной структуры приложения.
Если принимаете мое предложение, проверьте работу тестов.
Не удалось быстро запустить приложение и тесты по описанию из Readme.md

2022-08-08 18:24 UTC, roxblnfk commented on config/events-console.php
> +use App\Services\Timer;
Don't use plural form in namespaces

2022-08-09 05:42 UTC, xepozz requested changes
there is no structured modules

2022-08-09 06:11 UTC, arogachev commented
Could you briefly describe the difference?

2022-08-10 21:46 UTC, samdark commented
I agree with @xepozz. The proposed structure divides classes by-type rather than by use-case and that's not what we want to showcase. Structuring by use-case is preferred.

2022-08-10 21:48 UTC, samdark commented
Thanks for the effort but we'll stay with current demo structure and improve on it instead.

2022-08-10 21:48 UTC, closed without merging