Ignore inspector requests
yiisoft/demo pull request #551
Opened 2022-11-29 18:30 UTC by rustamwin

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2022-11-29 20:58 UTC, xepozz requested changes
Should be ignore in debug-api packages. AFAIR it's already there

2022-11-30 02:48 UTC, rustamwin commented
> AFAIR it's already there

I think you are confused with yii-debug config

2022-11-30 15:40 UTC, xepozz commented
> > AFAIR it's already there
> 
> I think you are confused with yii-debug config

You are right.

2022-11-30 15:40 UTC, xepozz approved these changes

2022-11-30 17:14 UTC, merged